// <auto-generated />
using System;
using LogisticsERP.API.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace LogisticsERP.API.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260627183336_Salary field is removed")]
    partial class Salaryfieldisremoved
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("LogisticsERP.API.Models.Driver", b =>
                {
                    b.Property<string>("DriverId")
                        .HasColumnType("text");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("CNIC")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("DateOfJoining")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("LicenseExpiry")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("LicenseNumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("LicenseUrl")
                        .HasColumnType("text");

                    b.Property<string>("MobileNumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PhotoUrl")
                        .HasColumnType("text");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("VehicleId")
                        .HasColumnType("text");

                    b.Property<string>("typeOfLicence")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("DriverId");

                    b.HasIndex("VehicleId");

                    b.ToTable("Drivers");
                });

            modelBuilder.Entity("LogisticsERP.API.Models.DutyLogs", b =>
                {
                    b.Property<string>("DutyId")
                        .HasColumnType("text");

                    b.Property<string>("ApprovedBy")
                        .HasColumnType("text");

                    b.Property<string>("CancellationReason")
                        .HasColumnType("text");

                    b.Property<DateTime?>("CancelledAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("DateIn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("DateOut")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Donor")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("DriverId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("DutyType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FromLocation")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal?>("KillometerIn")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("KillometerOut")
                        .HasColumnType("numeric");

                    b.Property<string>("OfficerName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Purpose")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Remarks")
                        .HasColumnType("text");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ToLocation")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal?>("TotalHours")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("TotalKm")
                        .HasColumnType("numeric");

                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.Property<string>("VehicleId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("DutyId");

                    b.HasIndex("DriverId");

                    b.HasIndex("UserId");

                    b.HasIndex("VehicleId");

                    b.ToTable("DutyLogs");
                });

            modelBuilder.Entity("LogisticsERP.API.Models.DutyRoster", b =>
                {
                    b.Property<string>("RosterId")
                        .HasColumnType("text");

                    b.Property<string>("ApprovedBy")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.Property<int>("Month")
                        .HasColumnType("integer");

                    b.Property<string>("Notes")
                        .HasColumnType("text");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Year")
                        .HasColumnType("integer");

                    b.HasKey("RosterId");

                    b.ToTable("DutyRosters");
                });

            modelBuilder.Entity("LogisticsERP.API.Models.DutyRosterEntry", b =>
                {
                    b.Property<string>("EntryId")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Donor")
                        .HasColumnType("text");

                    b.Property<string>("DriverId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("DutyDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("DutyLogId")
                        .HasColumnType("text");

                    b.Property<string>("DutyType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FromLocation")
                        .HasColumnType("text");

                    b.Property<string>("Notes")
                        .HasColumnType("text");

                    b.Property<string>("OfficerName")
                        .HasColumnType("text");

                    b.Property<string>("Purpose")
                        .HasColumnType("text");

                    b.Property<string>("RosterId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<TimeSpan>("ShiftEnd")
                        .HasColumnType("interval");

                    b.Property<TimeSpan>("ShiftStart")
                        .HasColumnType("interval");

                    b.Property<string>("ShiftType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ToLocation")
                        .HasColumnType("text");

                    b.Property<string>("VehicleId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("EntryId");

                    b.HasIndex("DriverId");

                    b.HasIndex("DutyLogId");

                    b.HasIndex("RosterId");

                    b.HasIndex("VehicleId");

                    b.ToTable("DutyRosterEntries");
                });

            modelBuilder.Entity("LogisticsERP.API.Models.Expense", b =>
                {
                    b.Property<string>("ExpenseId")
                        .HasColumnType("text");

                    b.Property<decimal>("Amount")
                        .HasColumnType("numeric");

                    b.Property<string>("ApprovedBy")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("ExpenseCategory")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("ExpenseDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("ExpenseName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ExpenseStatus")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Notes")
                        .HasColumnType("text");

                    b.Property<string>("PaymentMode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ReceiptNumber")
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("VehicleId")
                        .HasColumnType("text");

                    b.HasKey("ExpenseId");

                    b.HasIndex("UserId");

                    b.HasIndex("VehicleId");

                    b.ToTable("Expenses");
                });

            modelBuilder.Entity("LogisticsERP.API.Models.FuelRecord", b =>
                {
                    b.Property<string>("FuelId")
                        .HasColumnType("text");

                    b.Property<string>("AddedBy")
                        .HasColumnType("text");

                    b.Property<decimal>("CostPerLiter")
                        .HasColumnType("numeric");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Donor")
                        .HasColumnType("text");

                    b.Property<string>("DriverId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FuelType")
                        .HasColumnType("text");

                    b.Property<DateTime>("FuelingDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsFullTank")
                        .HasColumnType("boolean");

                    b.Property<decimal>("Liters")
                        .HasColumnType("numeric");

                    b.Property<int?>("Mileage")
                        .HasColumnType("integer");

                    b.Property<string>("Notes")
                        .HasColumnType("text");

                    b.Property<int>("OdoMeterReading")
                        .HasColumnType("integer");

                    b.Property<string>("PaymentMethod")
                        .HasColumnType("text");

                    b.Property<string>("Province")
                        .HasColumnType("text");

                    b.Property<string>("ReceiptNumber")
                        .HasColumnType("text");

                    b.Property<string>("StationLocation")
                        .HasColumnType("text");

                    b.Property<string>("StationName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("TotalCost")
                        .HasColumnType("numeric");

                    b.Property<string>("VehicleId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("FuelId");

                    b.HasIndex("DriverId");

                    b.HasIndex("VehicleId");

                    b.ToTable("FuelRecords");
                });

            modelBuilder.Entity("LogisticsERP.API.Models.MaintenanceRecord", b =>
                {
                    b.Property<string>("MaintenanceRecordId")
                        .HasColumnType("text");

                    b.Property<string>("AddedBy")
                        .HasColumnType("text");

                    b.Property<string>("ChangedParts")
                        .HasColumnType("text");

                    b.Property<decimal>("Cost")
                        .HasColumnType("numeric");

                    b.Property<decimal>("CurrentKm")
                        .HasColumnType("numeric");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("DriverId")
                        .HasColumnType("text");

                    b.Property<string>("InvoiceNumber")
                        .HasColumnType("text");

                    b.Property<DateTime>("MaintenanceDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("MaintenanceType")
                        .HasColumnType("text");

                    b.Property<DateTime?>("NextMaintenanceDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("NextMaintenanceFor")
                        .HasColumnType("text");

                    b.Property<decimal?>("NextMaintenanceKm")
                        .HasColumnType("numeric");

                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.Property<string>("VehicleId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("WorkshopName")
                        .HasColumnType("text");

                    b.HasKey("MaintenanceRecordId");

                    b.HasIndex("DriverId");

                    b.HasIndex("UserId");

                    b.HasIndex("VehicleId");

                    b.ToTable("MaintenanceRecords");
                });

            modelBuilder.Entity("LogisticsERP.API.Models.OvertimeDuty", b =>
                {
                    b.Property<string>("OvertimeDutyId")
                        .HasColumnType("text");

                    b.Property<string>("ApprovedBy")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("Date")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DriverId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("DutyId")
                        .HasColumnType("text");

                    b.Property<string>("DutyLogDutyId")
                        .HasColumnType("text");

                    b.Property<decimal>("Hours")
                        .HasColumnType("numeric");

                    b.Property<string>("Notes")
                        .HasColumnType("text");

                    b.Property<decimal?>("RatePerHour")
                        .HasColumnType("numeric");

                    b.Property<string>("Reason")
                        .HasColumnType("text");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal?>("TotalAmount")
                        .HasColumnType("numeric");

                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.HasKey("OvertimeDutyId");

                    b.HasIndex("DriverId");

                    b.HasIndex("DutyLogDutyId");

                    b.HasIndex("UserId");

                    b.ToTable("OvertimeDuties");
                });

            modelBuilder.Entity("LogisticsERP.API.Models.Role", b =>
                {
                    b.Property<string>("RoleId")
                        .HasColumnType("text");

                    b.Property<string>("RoleName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("RoleId");

                    b.ToTable("UserRole");
                });

            modelBuilder.Entity("LogisticsERP.API.Models.User", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ProfilePictureUrl")
                        .HasColumnType("text");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("UserId");

                    b.HasIndex("RoleId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("LogisticsERP.API.Models.Vehicle", b =>
                {
                    b.Property<string>("VehicleId")
                        .HasColumnType("text");

                    b.Property<string>("ChassisNumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Company")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("Depreciation")
                        .HasColumnType("numeric");

                    b.Property<string>("Doner")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("EngineNumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("FitnessExpiry")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime>("InsuranceExpiry")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime>("InsuranceFrom")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime>("InsuranceTo")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("InsuredBy")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ModelName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Number")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("PurchsedCast")
                        .HasColumnType("numeric");

                    b.Property<DateTime>("RegistrationDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime>("RegistrationExpiry")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("TypeOfInsurance")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("VehicleType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("VehicleId");

                    b.ToTable("Vehicles");
                });

            modelBuilder.Entity("LogisticsERP.API.Models.VehicleDocuments", b =>
                {
                    b.Property<string>("DocumentId")
                        .HasColumnType("text");

                    b.Property<string>("DocumentType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FileUrl")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PublicId")
                        .HasColumnType("text");

                    b.Property<DateTime>("UploadedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("VehicleId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("DocumentId");

                    b.HasIndex("VehicleId");

                    b.ToTable("VehicleDocuments");
                });

            modelBuilder.Entity("LogisticsERP.API.Models.Driver", b =>
                {
                    b.HasOne("LogisticsERP.API.Models.Vehicle", "Vehicle")
                        .WithMany("Drivers")
                        .HasForeignKey("VehicleId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Vehicle");
                });

            modelBuilder.Entity("LogisticsERP.API.Models.DutyLogs", b =>
                {
                    b.HasOne("LogisticsERP.API.Models.Driver", "Driver")
                        .WithMany("DutyLogs")
                        .HasForeignKey("DriverId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LogisticsERP.API.Models.User", "ApprovedByUser")
                        .WithMany()
                        .HasForeignKey("UserId");

                    b.HasOne("LogisticsERP.API.Models.Vehicle", "Vehicle")
                        .WithMany("DutyLogs")
                        .HasForeignKey("VehicleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ApprovedByUser");

                    b.Navigation("Driver");

                    b.Navigation("Vehicle");
                });

            modelBuilder.Entity("LogisticsERP.API.Models.DutyRosterEntry", b =>
                {
                    b.HasOne("LogisticsERP.API.Models.Driver", "Driver")
                        .WithMany()
                        .HasForeignKey("DriverId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LogisticsERP.API.Models.DutyLogs", "DutyLog")
                        .WithMany()
                        .HasForeignKey("DutyLogId");

                    b.HasOne("LogisticsERP.API.Models.DutyRoster", "Roster")
                        .WithMany("Entries")
                        .HasForeignKey("RosterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LogisticsERP.API.Models.Vehicle", "Vehicle")
                        .WithMany()
                        .HasForeignKey("VehicleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Driver");

                    b.Navigation("DutyLog");

                    b.Navigation("Roster");

                    b.Navigation("Vehicle");
                });

            modelBuilder.Entity("LogisticsERP.API.Models.Expense", b =>
                {
                    b.HasOne("LogisticsERP.API.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LogisticsERP.API.Models.Vehicle", "Vehicle")
                        .WithMany("Expanse")
                        .HasForeignKey("VehicleId");

                    b.Navigation("User");

                    b.Navigation("Vehicle");
                });

            modelBuilder.Entity("LogisticsERP.API.Models.FuelRecord", b =>
                {
                    b.HasOne("LogisticsERP.API.Models.Driver", "Driver")
                        .WithMany("FuelRecords")
                        .HasForeignKey("DriverId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LogisticsERP.API.Models.Vehicle", "Vehicle")
                        .WithMany("FuelRecords")
                        .HasForeignKey("VehicleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Driver");

                    b.Navigation("Vehicle");
                });

            modelBuilder.Entity("LogisticsERP.API.Models.MaintenanceRecord", b =>
                {
                    b.HasOne("LogisticsERP.API.Models.Driver", "Driver")
                        .WithMany("MaintenanceRecords")
                        .HasForeignKey("DriverId");

                    b.HasOne("LogisticsERP.API.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId");

                    b.HasOne("LogisticsERP.API.Models.Vehicle", "Vehicle")
                        .WithMany("MaintenanceRecords")
                        .HasForeignKey("VehicleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Driver");

                    b.Navigation("User");

                    b.Navigation("Vehicle");
                });

            modelBuilder.Entity("LogisticsERP.API.Models.OvertimeDuty", b =>
                {
                    b.HasOne("LogisticsERP.API.Models.Driver", "Driver")
                        .WithMany("OvertimeDuties")
                        .HasForeignKey("DriverId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LogisticsERP.API.Models.DutyLogs", "DutyLog")
                        .WithMany()
                        .HasForeignKey("DutyLogDutyId");

                    b.HasOne("LogisticsERP.API.Models.User", "ApprovedByUser")
                        .WithMany()
                        .HasForeignKey("UserId");

                    b.Navigation("ApprovedByUser");

                    b.Navigation("Driver");

                    b.Navigation("DutyLog");
                });

            modelBuilder.Entity("LogisticsERP.API.Models.User", b =>
                {
                    b.HasOne("LogisticsERP.API.Models.Role", "Role")
                        .WithMany("Users")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");
                });

            modelBuilder.Entity("LogisticsERP.API.Models.VehicleDocuments", b =>
                {
                    b.HasOne("LogisticsERP.API.Models.Vehicle", "Vehicle")
                        .WithMany("Documents")
                        .HasForeignKey("VehicleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Vehicle");
                });

            modelBuilder.Entity("LogisticsERP.API.Models.Driver", b =>
                {
                    b.Navigation("DutyLogs");

                    b.Navigation("FuelRecords");

                    b.Navigation("MaintenanceRecords");

                    b.Navigation("OvertimeDuties");
                });

            modelBuilder.Entity("LogisticsERP.API.Models.DutyRoster", b =>
                {
                    b.Navigation("Entries");
                });

            modelBuilder.Entity("LogisticsERP.API.Models.Role", b =>
                {
                    b.Navigation("Users");
                });

            modelBuilder.Entity("LogisticsERP.API.Models.Vehicle", b =>
                {
                    b.Navigation("Documents");

                    b.Navigation("Drivers");

                    b.Navigation("DutyLogs");

                    b.Navigation("Expanse");

                    b.Navigation("FuelRecords");

                    b.Navigation("MaintenanceRecords");
                });
#pragma warning restore 612, 618
        }
    }
}
